<?php
/**
 * ModelList
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MailMojo\Model;

use \ArrayAccess;

/**
 * ModelList Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     MailMojo
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ModelList implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'List';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'created' => '\DateTime',
        'description' => 'string',
        'facebook' => 'string',
        'from_email' => 'string',
        'from_name' => 'string',
        'id' => 'int',
        'instagram' => 'string',
        'linkedin' => 'string',
        'name' => 'string',
        'subscribe_redirect_url' => 'string',
        'subscribe_url' => 'string',
        'twitter' => 'string',
        'unsubscribe_cascades' => 'bool',
        'unsubscribe_redirect_url' => 'string',
        'unsubscribe_url' => 'string',
        'website' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'created' => 'created',
        'description' => 'description',
        'facebook' => 'facebook',
        'from_email' => 'from_email',
        'from_name' => 'from_name',
        'id' => 'id',
        'instagram' => 'instagram',
        'linkedin' => 'linkedin',
        'name' => 'name',
        'subscribe_redirect_url' => 'subscribe_redirect_url',
        'subscribe_url' => 'subscribe_url',
        'twitter' => 'twitter',
        'unsubscribe_cascades' => 'unsubscribe_cascades',
        'unsubscribe_redirect_url' => 'unsubscribe_redirect_url',
        'unsubscribe_url' => 'unsubscribe_url',
        'website' => 'website'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'created' => 'setCreated',
        'description' => 'setDescription',
        'facebook' => 'setFacebook',
        'from_email' => 'setFromEmail',
        'from_name' => 'setFromName',
        'id' => 'setId',
        'instagram' => 'setInstagram',
        'linkedin' => 'setLinkedin',
        'name' => 'setName',
        'subscribe_redirect_url' => 'setSubscribeRedirectUrl',
        'subscribe_url' => 'setSubscribeUrl',
        'twitter' => 'setTwitter',
        'unsubscribe_cascades' => 'setUnsubscribeCascades',
        'unsubscribe_redirect_url' => 'setUnsubscribeRedirectUrl',
        'unsubscribe_url' => 'setUnsubscribeUrl',
        'website' => 'setWebsite'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'created' => 'getCreated',
        'description' => 'getDescription',
        'facebook' => 'getFacebook',
        'from_email' => 'getFromEmail',
        'from_name' => 'getFromName',
        'id' => 'getId',
        'instagram' => 'getInstagram',
        'linkedin' => 'getLinkedin',
        'name' => 'getName',
        'subscribe_redirect_url' => 'getSubscribeRedirectUrl',
        'subscribe_url' => 'getSubscribeUrl',
        'twitter' => 'getTwitter',
        'unsubscribe_cascades' => 'getUnsubscribeCascades',
        'unsubscribe_redirect_url' => 'getUnsubscribeRedirectUrl',
        'unsubscribe_url' => 'getUnsubscribeUrl',
        'website' => 'getWebsite'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['facebook'] = isset($data['facebook']) ? $data['facebook'] : null;
        $this->container['from_email'] = isset($data['from_email']) ? $data['from_email'] : null;
        $this->container['from_name'] = isset($data['from_name']) ? $data['from_name'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['instagram'] = isset($data['instagram']) ? $data['instagram'] : null;
        $this->container['linkedin'] = isset($data['linkedin']) ? $data['linkedin'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['subscribe_redirect_url'] = isset($data['subscribe_redirect_url']) ? $data['subscribe_redirect_url'] : null;
        $this->container['subscribe_url'] = isset($data['subscribe_url']) ? $data['subscribe_url'] : null;
        $this->container['twitter'] = isset($data['twitter']) ? $data['twitter'] : null;
        $this->container['unsubscribe_cascades'] = isset($data['unsubscribe_cascades']) ? $data['unsubscribe_cascades'] : true;
        $this->container['unsubscribe_redirect_url'] = isset($data['unsubscribe_redirect_url']) ? $data['unsubscribe_redirect_url'] : null;
        $this->container['unsubscribe_url'] = isset($data['unsubscribe_url']) ? $data['unsubscribe_url'] : null;
        $this->container['website'] = isset($data['website']) ? $data['website'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['from_email'] === null) {
            $invalid_properties[] = "'from_email' can't be null";
        }
        if ($this->container['from_name'] === null) {
            $invalid_properties[] = "'from_name' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ($this->container['subscribe_redirect_url'] === null) {
            $invalid_properties[] = "'subscribe_redirect_url' can't be null";
        }
        if ($this->container['unsubscribe_redirect_url'] === null) {
            $invalid_properties[] = "'unsubscribe_redirect_url' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['from_email'] === null) {
            return false;
        }
        if ($this->container['from_name'] === null) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if ($this->container['subscribe_redirect_url'] === null) {
            return false;
        }
        if ($this->container['unsubscribe_redirect_url'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets created
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     * @param \DateTime $created
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets facebook
     * @return string
     */
    public function getFacebook()
    {
        return $this->container['facebook'];
    }

    /**
     * Sets facebook
     * @param string $facebook
     * @return $this
     */
    public function setFacebook($facebook)
    {
        $this->container['facebook'] = $facebook;

        return $this;
    }

    /**
     * Gets from_email
     * @return string
     */
    public function getFromEmail()
    {
        return $this->container['from_email'];
    }

    /**
     * Sets from_email
     * @param string $from_email
     * @return $this
     */
    public function setFromEmail($from_email)
    {
        $this->container['from_email'] = $from_email;

        return $this;
    }

    /**
     * Gets from_name
     * @return string
     */
    public function getFromName()
    {
        return $this->container['from_name'];
    }

    /**
     * Sets from_name
     * @param string $from_name
     * @return $this
     */
    public function setFromName($from_name)
    {
        $this->container['from_name'] = $from_name;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets instagram
     * @return string
     */
    public function getInstagram()
    {
        return $this->container['instagram'];
    }

    /**
     * Sets instagram
     * @param string $instagram
     * @return $this
     */
    public function setInstagram($instagram)
    {
        $this->container['instagram'] = $instagram;

        return $this;
    }

    /**
     * Gets linkedin
     * @return string
     */
    public function getLinkedin()
    {
        return $this->container['linkedin'];
    }

    /**
     * Sets linkedin
     * @param string $linkedin
     * @return $this
     */
    public function setLinkedin($linkedin)
    {
        $this->container['linkedin'] = $linkedin;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets subscribe_redirect_url
     * @return string
     */
    public function getSubscribeRedirectUrl()
    {
        return $this->container['subscribe_redirect_url'];
    }

    /**
     * Sets subscribe_redirect_url
     * @param string $subscribe_redirect_url
     * @return $this
     */
    public function setSubscribeRedirectUrl($subscribe_redirect_url)
    {
        $this->container['subscribe_redirect_url'] = $subscribe_redirect_url;

        return $this;
    }

    /**
     * Gets subscribe_url
     * @return string
     */
    public function getSubscribeUrl()
    {
        return $this->container['subscribe_url'];
    }

    /**
     * Sets subscribe_url
     * @param string $subscribe_url
     * @return $this
     */
    public function setSubscribeUrl($subscribe_url)
    {
        $this->container['subscribe_url'] = $subscribe_url;

        return $this;
    }

    /**
     * Gets twitter
     * @return string
     */
    public function getTwitter()
    {
        return $this->container['twitter'];
    }

    /**
     * Sets twitter
     * @param string $twitter
     * @return $this
     */
    public function setTwitter($twitter)
    {
        $this->container['twitter'] = $twitter;

        return $this;
    }

    /**
     * Gets unsubscribe_cascades
     * @return bool
     */
    public function getUnsubscribeCascades()
    {
        return $this->container['unsubscribe_cascades'];
    }

    /**
     * Sets unsubscribe_cascades
     * @param bool $unsubscribe_cascades
     * @return $this
     */
    public function setUnsubscribeCascades($unsubscribe_cascades)
    {
        $this->container['unsubscribe_cascades'] = $unsubscribe_cascades;

        return $this;
    }

    /**
     * Gets unsubscribe_redirect_url
     * @return string
     */
    public function getUnsubscribeRedirectUrl()
    {
        return $this->container['unsubscribe_redirect_url'];
    }

    /**
     * Sets unsubscribe_redirect_url
     * @param string $unsubscribe_redirect_url
     * @return $this
     */
    public function setUnsubscribeRedirectUrl($unsubscribe_redirect_url)
    {
        $this->container['unsubscribe_redirect_url'] = $unsubscribe_redirect_url;

        return $this;
    }

    /**
     * Gets unsubscribe_url
     * @return string
     */
    public function getUnsubscribeUrl()
    {
        return $this->container['unsubscribe_url'];
    }

    /**
     * Sets unsubscribe_url
     * @param string $unsubscribe_url
     * @return $this
     */
    public function setUnsubscribeUrl($unsubscribe_url)
    {
        $this->container['unsubscribe_url'] = $unsubscribe_url;

        return $this;
    }

    /**
     * Gets website
     * @return string
     */
    public function getWebsite()
    {
        return $this->container['website'];
    }

    /**
     * Sets website
     * @param string $website
     * @return $this
     */
    public function setWebsite($website)
    {
        $this->container['website'] = $website;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\MailMojo\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\MailMojo\ObjectSerializer::sanitizeForSerialization($this));
    }
}


