<?php
/**
 * HistoricalContactsStatsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailMojo;

/**
 * HistoricalContactsStatsTest Class Doc Comment
 *
 * @category    Class
 * @description HistoricalContactsStats
 * @package     MailMojo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoricalContactsStatsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HistoricalContactsStats"
     */
    public function testHistoricalContactsStats()
    {
    }

    /**
     * Test attribute "added"
     */
    public function testPropertyAdded()
    {
    }

    /**
     * Test attribute "bounced"
     */
    public function testPropertyBounced()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "sum"
     */
    public function testPropertySum()
    {
    }

    /**
     * Test attribute "unsubscribed"
     */
    public function testPropertyUnsubscribed()
    {
    }
}
