<?php
/**
 * ListDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailMojo;

/**
 * ListDetailTest Class Doc Comment
 *
 * @category    Class
 * @description ListDetail
 * @package     MailMojo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListDetail"
     */
    public function testListDetail()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "facebook"
     */
    public function testPropertyFacebook()
    {
    }

    /**
     * Test attribute "from_email"
     */
    public function testPropertyFromEmail()
    {
    }

    /**
     * Test attribute "from_name"
     */
    public function testPropertyFromName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "instagram"
     */
    public function testPropertyInstagram()
    {
    }

    /**
     * Test attribute "linkedin"
     */
    public function testPropertyLinkedin()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "pinterest"
     */
    public function testPropertyPinterest()
    {
    }

    /**
     * Test attribute "segments"
     */
    public function testPropertySegments()
    {
    }

    /**
     * Test attribute "subscribe_redirect_url"
     */
    public function testPropertySubscribeRedirectUrl()
    {
    }

    /**
     * Test attribute "subscribe_url"
     */
    public function testPropertySubscribeUrl()
    {
    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {
    }

    /**
     * Test attribute "unsubscribe_cascades"
     */
    public function testPropertyUnsubscribeCascades()
    {
    }

    /**
     * Test attribute "unsubscribe_redirect_url"
     */
    public function testPropertyUnsubscribeRedirectUrl()
    {
    }

    /**
     * Test attribute "unsubscribe_url"
     */
    public function testPropertyUnsubscribeUrl()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "youtube"
     */
    public function testPropertyYoutube()
    {
    }
}
