<?php
/**
 * NewsletterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailMojo;

/**
 * NewsletterTest Class Doc Comment
 *
 * @category    Class
 * @description Newsletter
 * @package     MailMojo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewsletterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Newsletter"
     */
    public function testNewsletter()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "editor_html"
     */
    public function testPropertyEditorHtml()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_aborted"
     */
    public function testPropertyIsAborted()
    {
    }

    /**
     * Test attribute "is_draft"
     */
    public function testPropertyIsDraft()
    {
    }

    /**
     * Test attribute "is_in_campaign"
     */
    public function testPropertyIsInCampaign()
    {
    }

    /**
     * Test attribute "is_scheduled"
     */
    public function testPropertyIsScheduled()
    {
    }

    /**
     * Test attribute "is_sending"
     */
    public function testPropertyIsSending()
    {
    }

    /**
     * Test attribute "is_sent"
     */
    public function testPropertyIsSent()
    {
    }

    /**
     * Test attribute "list"
     */
    public function testPropertyList()
    {
    }

    /**
     * Test attribute "meta"
     */
    public function testPropertyMeta()
    {
    }

    /**
     * Test attribute "num_recipients"
     */
    public function testPropertyNumRecipients()
    {
    }

    /**
     * Test attribute "plain"
     */
    public function testPropertyPlain()
    {
    }

    /**
     * Test attribute "saved"
     */
    public function testPropertySaved()
    {
    }

    /**
     * Test attribute "screenshot_url"
     */
    public function testPropertyScreenshotUrl()
    {
    }

    /**
     * Test attribute "segments"
     */
    public function testPropertySegments()
    {
    }

    /**
     * Test attribute "started"
     */
    public function testPropertyStarted()
    {
    }

    /**
     * Test attribute "statistics"
     */
    public function testPropertyStatistics()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "utm_campaign"
     */
    public function testPropertyUtmCampaign()
    {
    }

    /**
     * Test attribute "view_url"
     */
    public function testPropertyViewUrl()
    {
    }
}
