<?php
/**
 * PageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailMojo;

/**
 * PageTest Class Doc Comment
 *
 * @category    Class
 * @description Page
 * @package     MailMojo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Page"
     */
    public function testPage()
    {
    }

    /**
     * Test attribute "config"
     */
    public function testPropertyConfig()
    {
    }

    /**
     * Test attribute "confirmation_html"
     */
    public function testPropertyConfirmationHtml()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "editor_confirmation_html"
     */
    public function testPropertyEditorConfirmationHtml()
    {
    }

    /**
     * Test attribute "editor_html"
     */
    public function testPropertyEditorHtml()
    {
    }

    /**
     * Test attribute "expired_at"
     */
    public function testPropertyExpiredAt()
    {
    }

    /**
     * Test attribute "final_confirmation_html"
     */
    public function testPropertyFinalConfirmationHtml()
    {
    }

    /**
     * Test attribute "final_html"
     */
    public function testPropertyFinalHtml()
    {
    }

    /**
     * Test attribute "form_id"
     */
    public function testPropertyFormId()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "lid"
     */
    public function testPropertyLid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "published_at"
     */
    public function testPropertyPublishedAt()
    {
    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {
    }

    /**
     * Test attribute "subscribe_tags"
     */
    public function testPropertySubscribeTags()
    {
    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
