<?php
/**
 * TemplateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailMojo;

/**
 * TemplateTest Class Doc Comment
 *
 * @category    Class
 * @description Template
 * @package     MailMojo
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Template"
     */
    public function testTemplate()
    {
    }

    /**
     * Test attribute "campaign_expires_at"
     */
    public function testPropertyCampaignExpiresAt()
    {
    }

    /**
     * Test attribute "campaign_price"
     */
    public function testPropertyCampaignPrice()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "current_price"
     */
    public function testPropertyCurrentPrice()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_buyable"
     */
    public function testPropertyIsBuyable()
    {
    }

    /**
     * Test attribute "is_editable"
     */
    public function testPropertyIsEditable()
    {
    }

    /**
     * Test attribute "is_on_sale"
     */
    public function testPropertyIsOnSale()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "preview_url"
     */
    public function testPropertyPreviewUrl()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "product_type"
     */
    public function testPropertyProductType()
    {
    }

    /**
     * Test attribute "screenshot_url"
     */
    public function testPropertyScreenshotUrl()
    {
    }

    /**
     * Test attribute "settings"
     */
    public function testPropertySettings()
    {
    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {
    }

    /**
     * Test attribute "vat_amount"
     */
    public function testPropertyVatAmount()
    {
    }
}
