<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MailMojo;

use \MailMojo\Configuration;
use \MailMojo\ApiException;
use \MailMojo\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getContactByEmail
     *
     * Retrieve a contact in any list by email..
     *
     */
    public function testGetContactByEmail()
    {
    }

    /**
     * Test case for getContacts
     *
     * Retrieve all contacts across every list..
     *
     */
    public function testGetContacts()
    {
    }

    /**
     * Test case for getSubscriberOnListByEmail
     *
     * Retrieve a subscriber..
     *
     */
    public function testGetSubscriberOnListByEmail()
    {
    }

    /**
     * Test case for getSubscribersOnList
     *
     * Retrieve subscribers on a list..
     *
     */
    public function testGetSubscribersOnList()
    {
    }

    /**
     * Test case for getUnsubscribedOnList
     *
     * Retrieve unsubscribed contacts on a list..
     *
     */
    public function testGetUnsubscribedOnList()
    {
    }

    /**
     * Test case for subscribeContactToList
     *
     * Subscribe a contact to the email list..
     *
     */
    public function testSubscribeContactToList()
    {
    }

    /**
     * Test case for unsubscribeContactOnListByEmail
     *
     * Unsubscribe a contact..
     *
     */
    public function testUnsubscribeContactOnListByEmail()
    {
    }

    /**
     * Test case for updateContact
     *
     * Update details about a contact..
     *
     */
    public function testUpdateContact()
    {
    }
}
