<?php
/**
 * NewsletterApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * MailMojo API
 *
 * v1 of the MailMojo API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: hjelp@mailmojo.no
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MailMojo;

use \MailMojo\Configuration;
use \MailMojo\ApiException;
use \MailMojo\ObjectSerializer;

/**
 * NewsletterApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailMojo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NewsletterApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelNewsletter
     *
     * Cancel a newsletter..
     *
     */
    public function testCancelNewsletter()
    {
    }

    /**
     * Test case for createNewsletter
     *
     * Create a newsletter draft..
     *
     */
    public function testCreateNewsletter()
    {
    }

    /**
     * Test case for getNewsletterById
     *
     * Retrieve a newsletter by id..
     *
     */
    public function testGetNewsletterById()
    {
    }

    /**
     * Test case for getNewsletters
     *
     * Retrieve all newsletters..
     *
     */
    public function testGetNewsletters()
    {
    }

    /**
     * Test case for sendNewsletter
     *
     * Send a newsletter..
     *
     */
    public function testSendNewsletter()
    {
    }

    /**
     * Test case for testNewsletter
     *
     * Send a test newsletter..
     *
     */
    public function testTestNewsletter()
    {
    }

    /**
     * Test case for updateNewsletter
     *
     * Update a newsletter draft partially..
     *
     */
    public function testUpdateNewsletter()
    {
    }
}
